version: '3.7'

services:
  database_ignite:
    image: postgres:15
    container_name: database_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentx
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
     
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app 
    depends_on:
      - database_ignite
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge




