version: '3.7'

services:
  database_ignite:
    image: postgres:16
    container_name: database_ignite
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentx
    volumes:
      - /etc/postgresql/16/main:/etc/postgresql/16/main
    networks:
      - app-network
     
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app 
    depends_on:
      - database_ignite 
    networks:
      - app-network
 

networks:
  app-network:
    driver: host




